CREATE TABLE ABASTECIMENTO (
    CODIGO INTEGER NOT NULL,
    BOMBA INTEGER NOT NULL,
    TANQUE INTEGER NOT NULL,
    LITROS NUMERIC(9,4) NOT NULL,
    VALOR_LITRO NUMERIC(9,4) NOT NULL,
    VALOR_TOTAL NUMERIC(12,4) NOT NULL,
    ALIQUOTA NUMERIC(2,2) DEFAULT 0,
    VALOR_ALIQUOTA NUMERIC(12,4) NOT NULL,
    DATA_ABASTECIMENTO TIMESTAMP,
    CONSTRAINT INTEG_29 PRIMARY KEY (CODIGO)
);


CREATE OR ALTER SEQUENCE CODIGOABASTECIMENTO START WITH 1 INCREMENT BY 1;